# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.notificacion import Notificacion  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notificaciones: List[Notificacion]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param notificaciones: The notificaciones of this InlineResponse200.  # noqa: E501
        :type notificaciones: List[Notificacion]
        """
        self.swagger_types = {
            'notificaciones': List[Notificacion]
        }

        self.attribute_map = {
            'notificaciones': 'notificaciones'
        }
        self._notificaciones = notificaciones

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notificaciones(self) -> List[Notificacion]:
        """Gets the notificaciones of this InlineResponse200.

        array de notificaciones  # noqa: E501

        :return: The notificaciones of this InlineResponse200.
        :rtype: List[Notificacion]
        """
        return self._notificaciones

    @notificaciones.setter
    def notificaciones(self, notificaciones: List[Notificacion]):
        """Sets the notificaciones of this InlineResponse200.

        array de notificaciones  # noqa: E501

        :param notificaciones: The notificaciones of this InlineResponse200.
        :type notificaciones: List[Notificacion]
        """

        self._notificaciones = notificaciones
